#!/usr/bin/env python3
"""Generate the OpenRig projection from the plugins in this repo.

The plugins are the source of truth. This writes openrig/agents/<name>/ as a
projection so the two representations cannot drift: CI regenerates and diffs.

  python3 scripts/gen-openrig.py          # write
  python3 scripts/gen-openrig.py --check  # exit 1 if the projection is stale

Agent -> hub-skill comes from the routing table, not the directory layout: one
plugin can own several hub skills (aws owns two), and an agent missing from the
routing table is never dispatched, so it gets no seat either.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ROUTING = ROOT / "plugins/devops/skills/orchestrate/standards/routing-table.md"
OUT = ROOT / "openrig/agents"

# The orchestrator is not a dispatch target, so it is absent from the table.
LEAD = ("ops-lead", "devops", "orchestrate")

# Second runtime on one read-only seat: disagreement between two models is
# informative, and it exercises the codex path. Mirrors the adversarial-review
# precedent upstream.
RUNTIME = {"aws-investigator": "codex"}


CULTURE_SRC = ROOT / "rigs/CULTURE.md"
CULTURE_HEADER = ("<!-- GENERATED from rigs/CULTURE.md by scripts/gen-openrig.py — "
                  "edit that file, not this one.\n     OpenRig rejects `..` in culture_file, so each rig carries a copy. -->\n\n")


def culture_files() -> dict:
    """One culture per rig directory.

    A rig spec may not point at `../CULTURE.md` — the daemon rejects path
    traversal there — so the single source is copied in and drift-checked
    rather than maintained twice.
    """
    if not CULTURE_SRC.is_file():
        return {}
    body = CULTURE_HEADER + CULTURE_SRC.read_text(encoding="utf-8")
    return {rig.parent / "CULTURE.md": body
            for rig in sorted(ROOT.glob("rigs/*/rig.yaml"))}


def read(p):
    return p.read_text(encoding="utf-8")


def split_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        return {}, text
    fm = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith(" "):
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip()
    return fm, m.group(2).lstrip("\n")


def routing_rows():
    """(agent, plugin, hub) from the 'Domain -> agent' table."""
    rows = []
    for line in read(ROUTING).splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 4:
            continue
        agent, plugin, hub = (c.strip("`") for c in cells[1:4])
        if not re.fullmatch(r"[a-z0-9-]+", agent or ""):
            continue
        if not (ROOT / "plugins" / plugin).is_dir():
            continue
        rows.append((agent, plugin, hub))
    return rows


def agent_file(plugin, agent):
    p = ROOT / "plugins" / plugin / "agents" / f"{agent}.agent.md"
    return p if p.is_file() else None


def classify(description):
    """strict | gated | mutating — read off the description, not a hardcoded list."""
    d = description.lower()
    if "read-only" not in d and "read only" not in d:
        return "mutating"
    return "gated" if "apart from" in d else "strict"


def render(agent, plugin, hub, fm, klass):
    """One agent.yaml.

    Deliberately declares no skill resources. OpenRig resolves resource paths
    only INSIDE the agent spec directory — `..` is rejected — so declaring the
    plugin's hub skill as a resource would mean copying every action and
    standard into each of the twelve agent directories.

    Instead the seat runs the harness with this marketplace already installed,
    so the hub skill is available natively, and guidance/role.md carries the
    agent's own Skills table telling it which one to load. Referenced, never
    copied — just through the harness rather than through OpenRig.
    """
    runtime = RUNTIME.get(agent, "claude-code")
    desc = fm.get("description", "").strip().strip('"')
    summary = desc.split(".")[0][:120] if desc else agent
    access_note = {
        "strict": "  (strictly read-only by declaration: only can_observe edges may point at this seat)",
        "gated": "  (mutates only when asked for it)",
    }.get(klass, "  (mutating)")

    return "\n".join([
        "# GENERATED by scripts/gen-openrig.py from",
        f"# plugins/{plugin}/agents/{agent}.agent.md — edit that file, not this one.",
        f"name: {agent}",
        'version: "1.0"',
        f"description: {summary}",
        f"# access: {klass}{access_note}",
        f"# hub skill: {hub} (loaded from the installed plugin, named in guidance/role.md)",
        "defaults:",
        f"  runtime: {runtime}",
        "resources:",
        "  guidance:",
        "    - id: role",
        "      path: guidance/role.md",
        "profiles:",
        "  default:",
        "    uses:",
        "      guidance: [role]",
        "startup:",
        "  files:",
        "    - path: guidance/role.md",
        "      delivery_hint: send_text",
        "      required: true",
        "  actions: []",
        "",
    ])


def build():
    files, classes = {}, {}
    for agent, plugin, hub in [LEAD] + routing_rows():
        src = agent_file(plugin, agent)
        if src is None:
            print(f"  skip {agent}: no agent file under plugins/{plugin}/agents", file=sys.stderr)
            continue
        fm, body = split_frontmatter(read(src))
        klass = "mutating" if agent == LEAD[0] else classify(fm.get("description", ""))
        classes[agent] = klass
        files[f"{agent}/agent.yaml"] = render(agent, plugin, hub, fm, klass)
        files[f"{agent}/guidance/role.md"] = (
            f"<!-- GENERATED from plugins/{plugin}/agents/{agent}.agent.md — "
            f"edit that file, not this one. -->\n\n" + body
        )
    return files, classes


def main():
    check = "--check" in sys.argv
    files, classes = build()
    stale = []

    for dest, content in sorted(culture_files().items()):
        rel = dest.relative_to(ROOT)
        if check:
            if not dest.is_file() or read(dest) != content:
                stale.append(str(rel))
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
    for rel, content in sorted(files.items()):
        dest = OUT / rel
        if check:
            if not dest.is_file() or read(dest) != content:
                stale.append(rel)
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
    if check:
        existing = {str(p.relative_to(OUT)) for p in OUT.rglob("*") if p.is_file()} if OUT.is_dir() else set()
        orphans = sorted(existing - set(files))
        if stale or orphans:
            for f in stale:
                print(f"  stale: openrig/agents/{f}", file=sys.stderr)
            for f in orphans:
                print(f"  orphan: openrig/agents/{f}", file=sys.stderr)
            print("\nprojection is out of date — run: python3 scripts/gen-openrig.py", file=sys.stderr)
            return 1
        print(f"projection current ({len(files)} files, {len(classes)} agents)")
        return 0
    by = {}
    for a, k in classes.items():
        by.setdefault(k, []).append(a)
    print(f"wrote {len(files)} agent files + {len(culture_files())} rig culture file(s) "
          f"for {len(classes)} agents")
    for k in ("strict", "gated", "mutating"):
        if by.get(k):
            print(f"  {k:<9} {', '.join(sorted(by[k]))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
